POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Bobby",
  "dateOfBirth": "1999-03-03",
  "ssn": "12345678",
  "gender": "male",
  "occupation": "whaler"
}

###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Bobette",
  "dateOfBirth": "2000-02-02",
  "ssn": "12345678",
  "gender": "female",
  "occupation": "miner"
}


###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Boblin",
  "dateOfBirth": "1111-01-01",
  "ssn": "12345678",
  "gender": "other",
  "occupation": "farmer"
}


###
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Boblin",
  "dateOfBirth": "1111-91-01",
  "ssn": "12345678",
  "gender": "none",
  "occupation": 1
}

###
GET http://localhost:3001/api/patients

###
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2016-01-01",
  "type": "OccupationalHealthcare",
  "specialist": "MD House",
  "diagnosisCodes": [
    "S03.5"
  ],
  "description": "Really messed up",
  "employerName": "FBI",
  "sickLeave": {
    "startDate": "2016-01-01",
    "endDate": "2016-01-04"
  }
}


###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2016-01-01",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": [
    "S03.5"
  ],
  "description": "Really messed up",
  "discharge": {
    "date": "2016-01-06",
    "criteria": "All better!"
  }
}

###
POST http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667/entries
Content-Type: application/json

{
  "date": "2016-01-01",
  "type": "Hospital",
  "specialist": "MD House",
  "diagnosisCodes": [
    "S03.5"
  ],
  "description": "Really messed up"
}
